# Generated by Django 3.2.4 on 2021-07-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conid', models.CharField(max_length=200)),
                ('contype', models.CharField(max_length=25)),
            ],
        ),
    ]
