# Generated by Django 3.2.4 on 2021-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
