# Generated by Django 3.2.4 on 2021-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fb', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=10)),
                ('contype', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=8)),
                ('image', models.ImageField(upload_to='images')),
                ('planstartdate', models.DateField(max_length=10)),
                ('planenddate', models.DateField(max_length=10)),
            ],
        ),
    ]
