# Generated by Django 3.2.4 on 2021-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=50)),
                ('charges', models.TextField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
