# Generated by Django 3.2.4 on 2021-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='charges',
            field=models.CharField(max_length=50),
        ),
    ]
