# Generated by Django 3.2.4 on 2021-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_plan_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plantype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='fb',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='instagram',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='linkedin',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='twitter',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.URLField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='youtube',
            field=models.URLField(max_length=50),
        ),
    ]
