# Generated by Django 3.2.4 on 2021-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_department_depcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('rtype', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='depcontact',
            name='contactno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='depcontact',
            name='depid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depcontact',
            name='designation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='depcontact',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='depcontact',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depcontact',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='depcontact',
            name='depcid',
            field=models.CharField(max_length=10),
        ),
    ]
