# Generated by Django 3.2.4 on 2021-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210717_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('joiningdate', models.DateField(max_length=10)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
