# Generated by Django 3.2.4 on 2021-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_inward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outwardno', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
