# Generated by Django 3.2.4 on 2021-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_outward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=10)),
                ('hname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
