# Generated by Django 3.2.4 on 2021-07-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('adhaarcard', models.CharField(max_length=12)),
                ('refname', models.CharField(max_length=20)),
                ('refcontact', models.CharField(max_length=10)),
                ('datefrom', models.DateTimeField(max_length=10)),
                ('dateto', models.DateTimeField(max_length=10)),
                ('reason', models.TextField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.TimeField()),
                ('checkin', models.TimeField()),
                ('upcoming', models.CharField(blank=True, max_length=20)),
                ('past', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.reservation')),
            ],
        ),
    ]
