# Generated by Django 3.2.4 on 2021-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_reservation_reservationview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationview',
            name='upcoming',
            field=models.CharField(max_length=20),
        ),
    ]
