# Generated by Django 3.2.4 on 2021-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_reservationview_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationview',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
