# Generated by Django 3.2.4 on 2021-07-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_reservationview_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=15)),
                ('From', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('takeoffdate', models.DateTimeField(max_length=10)),
                ('landingdate', models.DateTimeField(max_length=10)),
                ('PNR', models.CharField(max_length=10)),
                ('ticketamt', models.CharField(max_length=10)),
                ('boardingpassimage', models.ImageField(upload_to='images')),
                ('invoiceimage', models.ImageField(upload_to='images')),
                ('journeytype', models.CharField(max_length=15)),
                ('distance', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='inward',
            name='Remark',
            field=models.IntegerField(null=True),
        ),
    ]
