# Generated by Django 3.2.4 on 2021-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20210718_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightentry',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
